### ISSUE TITLE
Add correct answers to the hunt definition and API

### ISSUE THREAD

**Issue by obijywk** [eastern-toys/Cube#15]
we probably need two types of Answer (acceptable and canonical) and allow for multiple canonical Answers per puzzle id. we'll need to display canonical answers once a team has solved, and we'll want to display them in the call queue.

**Comment by tkfocht** [comment]
That looks like the summary I should have written earlier this evening. :)

Answers probably need their own associated Visibilities that are set by workflow alongside status for a puzzle.

**Comment by tkfocht** [comment]
I take it back on Answers having their own Visibilities. The Visibility status for the puzzle should control what (if any) Answers are returned on /answers/<puzzle_id>. That minimizes the number of things that have to be controlled.
